export const advisors_students = [
  //High School || 0-4
  {
    id: 1,
    name: "ieltszerofourhigh@gmail.com",
    status: "Eligible",
    scale: "0-4",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 2,
    name: "ieltszerofourmid@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 3,
    name: "ieltszerofourlow@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },

  {
    id: 4,
    name: "ptezerofourlow@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 5,
    name: "ptezerofourmid@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },

  {
    id: 6,
    name: "ptezerofourhigh@gmail.com",
    status: "Eligible",
    scale: "0-4",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },

  {
    id: 7,
    name: "duolingozerofourlow@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 8,
    name: "duolingozerofourmid@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 9,
    name: "duolingozerofourhigh@gmail.com",
    status: "Eligible",
    scale: "0-4",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },

  {
    id: 10,
    name: "toeflzerofourlow@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 11,
    name: "toeflzerofourmid@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 12,
    name: "toeflzerofourhigh@gmail.com",
    status: "Eligible",
    scale: "0-4",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  //0-4 || Bachelors
  {
    id: 13,
    name: "ieltszerofourbachelors@gmail.com",
    status: "Eligible",
    scale: "0-4",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 14,
    name: "ieltszerofourbachelorsmidscore@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 15,
    name: "ieltszerofourlowscorebachelors@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 16,
    name: "ptezerofourlowscorebachelors@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 17,
    name: "ptezerofourmidscorebachelors@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 18,
    name: "ptezerofourhighscorebachelors@gmail.com",
    status: "Eligible",
    scale: "0-4",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 19,
    name: "duolingozerofourlowbachelors@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 20,
    name: "duolingozerofourmidbachelors@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 21,
    name: "duolingozerofourhighbachelors@gmail.com",
    status: "Eligible",
    scale: "0-4",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 22,
    name: "toeflzerofourlowbachelors@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 23,
    name: "toeflzerofourmidbachelors@gmail.com",
    status: "Not Eligible",
    scale: "0-4",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 24,
    name: "toeflzerofourhighbachelors@gmail.com",
    status: "Eligible",
    scale: "0-4",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  // High school || 1- 100
  {
    id: 25,
    name: "ieltsonehundredhigh@gmail.com",
    status: "Eligible",
    scale: "1-100",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 26,
    name: "ieltsonehundredmid@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 27,
    name: "ieltsonehundredlow@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 28,
    name: "pteonehundredlow@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 29,
    name: "pteonehundredmid@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 30,
    name: "pteonehundredhigh@gmail.com",
    status: "Eligible",
    scale: "1-100",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 31,
    name: "duolingoonehundredlow@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 32,
    name: "duolingoonehundredmid@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 33,
    name: "duolingoonehundredhigh@gmail.com",
    status: "Eligible",
    scale: "1-100",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 34,
    name: "toeflonehundredlow@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 35,
    name: "toeflonehundredmid@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  {
    id: 36,
    name: "toeflonehundredhigh@gmail.com",
    status: "Eligible",
    scale: "1-100",
    level_of_study: "High School",
    apply_for: "Bachelor's Degree",
  },
  // Bachelors || 1 - 100
  {
    id: 37,
    name: "ieltsonehundredbachelorshigh@gmail.com",
    status: "Eligible",
    scale: "1-100",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 38,
    name: "ieltsonehundredbachelorsmid@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 39,
    name: "ieltsonehundredlowbachelors@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 40,
    name: "ieltsonehundredlowbachelors@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 41,
    name: "pteonehundredbachelorslow@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 42,
    name: "pteonehundredbacjelorsmid@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 43,
    name: "pteonehundredbachelorshigh@gmail.com",
    status: "Eligible",
    scale: "1-100",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 44,
    name: "duolingoonehundredbachelorslow@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 45,
    name: "duolingoonehundredbachelorsmid@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 46,
    name: "duolingoonehundredbachelorshigh@gmail.com",
    status: "Eligible",
    scale: "1-100",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 47,
    name: "toeflonehundredbachelorslow@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 48,
    name: "toeflonehundredbachelorsmid@gmail.com",
    status: "Not Eligible",
    scale: "1-100",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
  {
    id: 49,
    name: "toeflonehundredbachelorshigh@gmail.com",
    status: "Eligible",
    scale: "1-100",
    level_of_study: "Bachelors",
    apply_for: "Master's Degree",
  },
];
